### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by nk932714** [guyrotem/google-translate-server#3]
Please check its not working now

![image](https://user-images.githubusercontent.com/29853208/43118442-825c965a-8f2f-11e8-8b83-05ede40ddd5f.png)

**Comment by guyrotem** [comment]
thanks for reporting! seems like Google use some IP based throttling on calls to translate API and redirect the requests to a captcha. there are too many requests from my demo app. I might implement throttling on my end too, but free usage has its limits...
if anyone wants to deploy this code on their own server, it should probably work

**Comment by nk932714** [comment]
Thanks i'll try to deploy and let you know if it is working

**Comment by guyrotem** [comment]
every time I redeploy it on Heroku it works for a while (getting a new IP?), then Google block it again due to some unusual traffic detected (I don't monitor too much who is using this API, could be really high throughput or just sensitive captcha threshold)

**Comment by nk932714** [comment]
Thanks a lot buddy for this beautiful repo. Its working fine.
